
#define MAX_LINE_LENGTH 80
#define MAX_LINE_WITH_LINEDROP_LEN 82
#define IC_INIT_VALUE 100
#define DC_INIT_VALUE 0
#define MAX_SYMBOL_SIZE 31
#define MAX_MACHINE_CODE_SECTION 8192
#define MAX_MACHINE_DATA_SECTION 8192
#define NUM_OF_RESERVED_WORDS 36
#define NUM_OF_OPCODES 16

#define TRUE 1
#define FALSE 0
